### ISSUE TITLE
reel.values 3x3 why need 

### ISSUE THREAD

**Issue by c4ei** [ktsalik/slot#11]
reel.values 3x3 why need 1?

// initial values
  reel.values = [**1**, 1, 2, 3];

**Comment by ktsalik** [comment]
It's because how reels work. If we had a different aproach in the class Reel, we might not needed it. For now it's the hidden symbol above the first (top). When you press play there must be an animation between the first (top) seen and the one above it (the new coming out). When reels start the 4rth (hidden) becomes the 3rd (top) with and offset from top as someone pushes it. That gives time to another fourth (hidden) to be prepared for the cathode.

**Comment by c4ei** [comment]
really thank you (__)
